CREATE OR REPLACE TRIGGER Fide_Canton_TB_InsertID_TRG
BEFORE INSERT ON Fide_Canton_TB
FOR EACH ROW
BEGIN
:NEW.ID_CANTON:=FIDE_ProyectoLenguajes_PCK.Fide_Canton_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER Fide_Categorias_TB_InsertID_TRG
BEFORE INSERT ON Fide_Categorias_TB
FOR EACH ROW
BEGIN
:NEW.ID_CATEGORIA:=FIDE_ProyectoLenguajes_PCK.Fide_Categorias_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER Fide_Claves_TB_InsertID_TRG
BEFORE INSERT ON Fide_Claves_TB
FOR EACH ROW
BEGIN
:NEW.ID_CLAVE:=FIDE_ProyectoLenguajes_PCK.Fide_Claves_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER Fide_Clientes_TB_InsertID_TRG
BEFORE INSERT ON Fide_Clientes_TB
FOR EACH ROW
BEGIN
:NEW.ID_CLIENTE:=FIDE_ProyectoLenguajes_PCK.Fide_Clientes_TB_GENERARID_SEQ_FN();
END;

/
CREATE OR REPLACE TRIGGER Fide_Colaboradores_TB_InsertID_TRG
BEFORE INSERT ON Fide_Colaboradores_TB
FOR EACH ROW
BEGIN
:NEW.ID_COLABORADOR:=FIDE_ProyectoLenguajes_PCK.Fide_Colaboradores_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER Fide_Distrito_TB_InsertID_TRG
BEFORE INSERT ON Fide_Distrito_TB
FOR EACH ROW
BEGIN
:NEW.ID_DISTRITO:=FIDE_ProyectoLenguajes_PCK.Fide_Distrito_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER Fide_Estado_TB_InsertID_TRG
BEFORE INSERT ON Fide_Estado_TB
FOR EACH ROW
BEGIN
:NEW.ID_ESTADO:=FIDE_ProyectoLenguajes_PCK.Fide_Estado_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER FIDE_HeaderFactura_TB_InsertID_TRG
BEFORE INSERT ON FIDE_HeaderFactura_TB
FOR EACH ROW
BEGIN
:NEW.ID_FACTURA:=FIDE_ProyectoLenguajes_PCK.FIDE_HeaderFactura_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_HistorialCompras_TB_InsertID_TRG
BEFORE INSERT ON FIDE_HistorialCompras_TB
FOR EACH ROW
BEGIN
:NEW.ID_HISTORIAL:=FIDE_ProyectoLenguajes_PCK.FIDE_HistorialCompras_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Provincia_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Provincia_TB
FOR EACH ROW
BEGIN
:NEW.ID_PROVINCIA:=FIDE_ProyectoLenguajes_PCK.FIDE_Provincia_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Ubicacion_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Ubicacion_TB
FOR EACH ROW
BEGIN
:NEW.ID_UBICACION:=FIDE_ProyectoLenguajes_PCK.FIDE_Ubicacion_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Roles_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Roles_TB
FOR EACH ROW
BEGIN
:NEW.ID_ROL:=FIDE_ProyectoLenguajes_PCK.FIDE_Roles_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Producto_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Producto_TB
FOR EACH ROW
BEGIN
:NEW.ID_PRODUCTO:=FIDE_ProyectoLenguajes_PCK.FIDE_Producto_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Horarios_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Horarios_TB
FOR EACH ROW
BEGIN
:NEW.ID_HORARIO:=FIDE_ProyectoLenguajes_PCK.FIDE_Horarios_TB_GENERARID_SEQ_FN();
END;

CREATE OR REPLACE TRIGGER Fide_Proveedores_TB_InsertID_TRG
BEFORE INSERT ON Fide_Proveedores_TB
FOR EACH ROW
BEGIN
:NEW.ID_PROVEEDOR:=FIDE_ProyectoLenguajes_PCK.Fide_Proveedores_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER Fide_Venta_TB_InsertID_TRG
BEFORE INSERT ON Fide_Venta_TB
FOR EACH ROW
BEGIN
:NEW.ID_VENTA:=FIDE_ProyectoLenguajes_PCK.Fide_Venta_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER Fide_PedidoProveedor_TB_InsertID_TRG
BEFORE INSERT ON Fide_PedidoProveedor_TB
FOR EACH ROW
BEGIN
:NEW.ID_PEDIDOPROVEEDOR:=FIDE_ProyectoLenguajes_PCK.Fide_PedidoProveedor_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Promociones_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Promociones_TB
FOR EACH ROW
BEGIN
:NEW.ID_PROMOCIONES:=FIDE_ProyectoLenguajes_PCK.FIDE_Promociones_TB_GENERARID_SEQ_FN();
END;


CREATE OR REPLACE TRIGGER FIDE_Inventario_TB_InsertID_TRG
BEFORE INSERT ON FIDE_Inventario_TB
FOR EACH ROW
BEGIN
:NEW.ID_INVENTARIO:=FIDE_ProyectoLenguajes_PCK.FIDE_Inventario_TB_GENERARID_SEQ_FN();
END;

CREATE OR REPLACE TRIGGER FIDE_HistorialProducto_TB_InsertID_TRG
BEFORE INSERT ON FIDE_HistorialProducto_TB
FOR EACH ROW
BEGIN
:NEW.ID_HISTORIALPRODUCTO:=FIDE_ProyectoLenguajes_PCK.FIDE_HistorialProducto_TB_GENERARID_SEQ_FN();
END;

/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_InsertID_TRG
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
:NEW.ID_CARRITO:=FIDE_ProyectoLenguajes_PCK.FIDE_CARRITO_TB_GENERARID_SEQ_FN();
END;


