-- creacion de triggers para la tabla canton 

CREATE OR REPLACE TRIGGER Fide_Canton_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON Fide_Canton_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER Fide_Canton_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON Fide_Canton_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER Fide_Canton_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON Fide_Canton_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla categorias 

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla Claves 

CREATE OR REPLACE TRIGGER FIDE_CLAVES_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_CLAVES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CLAVES_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_CLAVES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CLAVES_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLAVES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla clientes 

CREATE OR REPLACE TRIGGER FIDE_CLientes_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_CLientes_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CLientes_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_CLientes_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_CLientes_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLientes_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla colaboradores 

CREATE OR REPLACE TRIGGER FIDE_COLABORADORES_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_COLABORADORES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_COLABORADORES_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_COLABORADORES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_COLABORADORES_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_COLABORADORES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla detalleFactura 

CREATE OR REPLACE TRIGGER FIDE_DETALLEFACTURA_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_DETALLEFACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLEFACTURA_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_DETALLEFACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLEFACTURA_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLEFACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla detallepedidoProveedor 

CREATE OR REPLACE TRIGGER FFIDE_DETALLEPEDIPOPROVEEDOR_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_DETALLEPEDIPOPROVEEDOR_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLEPEDIPOPROVEEDOR_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_DETALLEPEDIPOPROVEEDOR_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLEPEDIPOPROVEEDOR_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLEPEDIPOPROVEEDOR_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla distrito 

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla estado 

CREATE OR REPLACE TRIGGER FFIDE_ESTADO_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla headerfactura 

CREATE OR REPLACE TRIGGER FIDE_HEADERFACTURA_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_HEADERFACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HEADERFACTURA_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_HEADERFACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HEADERFACTURA_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_HEADERFACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla historialCompras 

CREATE OR REPLACE TRIGGER FIDE_HISTORIALCOMPRAS_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_HISTORIALCOMPRAS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HISTORIALCOMPRAS_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_HISTORIALCOMPRAS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HISTORIALCOMPRAS_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALCOMPRAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla historialproducto

CREATE OR REPLACE TRIGGER FIDE_HISTORIALPRODUCTO_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_HISTORIALPRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HISTORIALPRODUCTO_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_HISTORIALPRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HISTORIALPRODUCTO_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALPRODUCTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla horarios
CREATE OR REPLACE TRIGGER FIDE_HORARIOS_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_HORARIOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HORARIOS_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_HORARIOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_HORARIOS_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_HORARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla inventario

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;


//////////////

-- creacion de triggers para la tabla pedido proveedor

CREATE OR REPLACE TRIGGER FIDE_PEDIDOPROVEEDOR_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PEDIDOPROVEEDOR_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PEDIDOPROVEEDOR_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PEDIDOPROVEEDOR_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PEDIDOPROVEEDOR_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDOPROVEEDOR_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla producto

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla productoPromocion

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOSPROMOCION_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PRODUCTOSPROMOCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOSPROMOCION_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PRODUCTOSPROMOCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOSPROMOCION_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOSPROMOCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla Promociones

CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla proveedores

CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla provincia

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla roles

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla ubicacion

CREATE OR REPLACE TRIGGER FIDE_UBICACION_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_UBICACION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_UBICACION_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_UBICACION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_UBICACION_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_UBICACION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

-- creacion de triggers para la tabla venta

CREATE OR REPLACE TRIGGER FIDE_VENTA_TB_Auditorias_Creacion_TRG
BEFORE INSERT ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_VENTA_TB_Auditorias_Modificacion_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ULTIMA_ACTUALIZACION_POR:=USER;
END;

CREATE OR REPLACE TRIGGER FIDE_VENTA_TB_Auditorias_Accion_TRG
BEFORE INSERT OR UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

//////////////

