CREATE OR REPLACE TRIGGER Fide_Canton_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Categorias_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_CAtegorias_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Claves_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Claves_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Clientes_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Clientes_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_DetalleFactura_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_DetalleFactura_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_DetallePedidoProveedor_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_DetallePedipoProveedor_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Distrito_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Distrito_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_headerFactura_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_headerFactura_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_historialCompras_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_historialCompras_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_historialProducto_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_historialProducto_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_horarios_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_horarios_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_inventario_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_inventario_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_PedidoProveedor_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_PedidoProveedor_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Producto_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Producto_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_ProductosPromocion_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_ProductosPromocion_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Promociones_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Promociones_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Proveedores_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Proveedores_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Provincia_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Provincia_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Roles_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Roles_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Ubicacion_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Ubicacion_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

CREATE OR REPLACE TRIGGER Fide_Venta_TB_InsertEstado_TRG
BEFORE INSERT ON FIDE_Venta_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO_FK := 1;
END;

